---
abstract: 'Calculate Availability Data from'
author:
  - 'Sven Nierlein, <nierlein@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitoring-Availability
no_index:
  directory:
    - inc
    - t
requires:
  Test::More: 0.87
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.40
